"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ  # 환경변수 추가
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 파트 4. env세팅
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "todo",
    "rest_framework",
    "accounts",  # Part 7
    "interaction",  # Part 10
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Part 6, 미디어파일 관련 설정
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# DRF 브라우저용 HTML 화면을 끄고, 무조건 JSON만 응답하게 하는 옵션
# API 서버만 사용하고, 브라우저에서 DRF 화면 필요 없을 때 (React/모바일 이용)
# REST_FRAMEWORK = {
#     # 기본권한 설정: 누구나 API에 접근 가능(개발시 사용)
#     "DEFAULT_PERMISSION_CLASSES": [
#         "rest_framework.permissions.AllowAny",
#     ],
#     # 기본 페이지네이션 설정
#     "DEFAULT_PAGINATION_CLASS": "todo.pagination.CustomPageNumberPagination",
#     "PAGE_SIZE": 3,
#     # API응답형식
#     "DEFAULT_RENDERER_CLASSES": [
#         "rest_framework.renderers.JSONRenderer",
#         "rest_framework.renderers.BrowsableAPIRenderer",
#     ],
#     #
# }

# Part 7
REST_FRAMEWORK = {
    # 인증: 요청자가 누구인지 확인하는 방식
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # JWT 우선
        # 2) 전환기 안전장치(선택): 기존 세션도 허용
        #    모든 프론트가 JWT로 바뀐 후 제거 가능
        "rest_framework.authentication.SessionAuthentication",
    ],
    # 권한: 로그인한 사용자만 API 접근 허용
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # 페이지네이션: 목록 API를 3개씩 나눠서 반환
    "DEFAULT_PAGINATION_CLASS": "todo.pagination.CustomPageNumberPagination",
    "PAGE_SIZE": 3,
    # 렌더러: 응답 형식 지정
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",  # JSON (실서비스)
        "rest_framework.renderers.BrowsableAPIRenderer",  # DRF 웹 UI (개발용)
    ],
}

# Part 7
# # 인증: 요청자가 누구인지 확인하는 방식
#     "DEFAULT_AUTHENTICATION_CLASSES": [
#         "rest_framework.authentication.SessionAuthentication",  # 세션 (브라우저)
#         "rest_framework.authentication.BasicAuthentication",  # ID/PW 직접 전달
#     ],

# 만료 시간/헤더 타입
SIMPLE_JWT = {
    # access는 짧게(보안), refresh는 길게(편의)
    # access = 보통 5분, refresh = 보통 1일 기간을 설정한다.
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=300),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365),
    # Authorization: Bearer <token>
    "AUTH_HEADER_TYPES": ("Bearer",),
    # (5~6단계에서 다룰 것들 - 지금은 False로 두고 시작 권장)
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
}
